### ISSUE TITLE
Input: 

### ISSUE THREAD

**Issue by koekemoer** [charl26/Abstract-VM#24] opened 2017-07-12 06:18 UTC
when testing the sample file it gives invalid input because there is an empty line at the end of the input.

**Comment by ScheepersDev23** [comment] 2017-07-14 08:14
This most probably happens because the exit function has not yet been implemented. So technically it's not a bug, we'll have to re-test this issue when we've implemented the exit function. For now, let's close the issue and mark it as resolved, if the issue persists, we can reopen it.

**Closed as completed** 2017-07-14 08:29 UTC
Labels: bug, In Progress
